import { Inter } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import Footer from '@/components/Footer/Footer';
import Navbar from '@/components/Header/Navbar';
import TopBar from '@/components/Header/Topbar';
import Container from '@/components/HigherOrder/Container';


import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {/* {children} */}
          <div
            // className="w-[100vw] h-[100vh]"
            className="h-[100vh]"
            style={{
              background: "url('/assets/HeroBackground.jpg')",
              backgroundPosition: 'center',
              backgroundRepeat: 'no-repeat',
              backgroundSize: 'cover',
            }}
          >
            <Container
              Component={<TopBar />}
              restClasses="flex bg-[rgba(0,0,0,0.6)]"
            />
            <Container
              Component={<Navbar />}
              pymd="20px"
              restClasses="border-t-white border-b-white border-t-[1px] border-b-[1px] bg-[rgba(0,0,0,0.6)] hidden md:block"
            />
            {children}
            <Container
              Component={<Footer />}
              // restClasses="border-t-[2px] border-t-[#ccc] mt-5 bg-gradient-to-r from-[#283606] to-[#0F1500] absolute bottom-0 w-[100%]"
              restClasses="border-t-[2px] border-t-[#ccc] bg-gradient-to-r from-[#283606] to-[#0F1500]"
            />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
